"""Tests for the run-history store (plain JSON Lines, not SQLite -- see
engine/history_store.py's module docstring for why)."""

from __future__ import annotations

from settlegraph.engine.history_store import (
    check_cross_run_drift,
    get_metric_series,
    list_runs,
    record_run,
)


def _summary(precision: float = 1.0, exception_rate: float = 0.01) -> dict:
    return {
        "records": {"razorpay": 100, "bank": 100, "merchant": 100},
        "evaluation": {
            "precision": precision,
            "recall": 0.85,
            "f1": 0.9,
            "exception_rate": exception_rate,
            "false_match_rate": 0.0,
            "ai_assisted_matches": 0,
        },
        "throughput": {"records_per_second": 500.0},
        "drift": {"drift_detected": False},
    }


def test_history_file_is_plain_jsonl_not_a_binary_db(tmp_path) -> None:
    """Ponytail audit finding: everything this store actually does --
    append a row, list recent rows sorted by time, read one column as a
    chronological series -- is a few lines over a flat file. SQLite added
    a schema, a connection lifecycle, and a query-construction surface for
    operations this simple, and it broke with every other output this
    project produces (assignments.csv, exceptions.json, ...): a file you
    can `cat`/`tail`/`grep` without a client, which is a real advantage for
    a project whose whole ethos is an inspectable audit trail. This pins
    the replacement: the history file must be plain UTF-8 JSON Lines,
    directly parseable line by line with the stdlib `json` module alone."""
    history_path = tmp_path / "history.jsonl"
    record_run(history_path, _summary())
    record_run(history_path, _summary(exception_rate=0.02))

    raw = history_path.read_text(encoding="utf-8")
    lines = [line for line in raw.splitlines() if line.strip()]
    assert len(lines) == 2

    import json

    parsed = [json.loads(line) for line in lines]
    assert parsed[0]["exception_rate"] == 0.01
    assert parsed[1]["exception_rate"] == 0.02


def test_record_and_list_round_trip(tmp_path) -> None:
    db_path = tmp_path / "history.jsonl"
    run_id = record_run(db_path, _summary())
    runs = list_runs(db_path)
    assert len(runs) == 1
    assert runs[0]["run_id"] == run_id
    assert runs[0]["precision"] == 1.0
    assert runs[0]["total_records"] == 300


def test_record_run_accepts_a_pre_generated_run_id(tmp_path) -> None:
    """Code-review finding: summary.json needs to carry its own run_id
    *before* it's written to disk, which means the id has to exist before
    record_run is called, not be generated by it. record_run must accept
    (and actually use) a caller-supplied id rather than always minting its
    own."""
    db_path = tmp_path / "history.jsonl"
    given_id = "fixed-test-id-1234"

    returned_id = record_run(db_path, _summary(), run_id=given_id)

    assert returned_id == given_id
    assert list_runs(db_path)[0]["run_id"] == given_id


def test_list_runs_on_missing_db_returns_empty_not_an_error(tmp_path) -> None:
    assert list_runs(tmp_path / "nonexistent.db") == []


def test_metric_series_is_chronological_oldest_first(tmp_path) -> None:
    db_path = tmp_path / "history.jsonl"
    record_run(db_path, _summary(exception_rate=0.01))
    record_run(db_path, _summary(exception_rate=0.02))
    record_run(db_path, _summary(exception_rate=0.03))
    series = get_metric_series(db_path, "exception_rate")
    assert series == [0.01, 0.02, 0.03]


def test_unsupported_metric_is_rejected() -> None:
    """An arbitrary string must never silently look up as a metric --
    checked against an explicit allowlist, not just "does this key exist
    in the row." A stray typo (or, from before the SQLite -> JSONL
    ponytail pass, a SQL-injection-shaped string) gets the same clean
    ValueError either way."""
    import pytest

    with pytest.raises(ValueError, match="Unsupported metric"):
        get_metric_series(__import__("pathlib").Path("x.jsonl"), "'; DROP TABLE runs;--")


def test_cross_run_drift_is_honest_about_insufficient_history(tmp_path) -> None:
    db_path = tmp_path / "history.jsonl"
    record_run(db_path, _summary())
    record_run(db_path, _summary())
    result = check_cross_run_drift(db_path)
    assert result["status"] == "insufficient_history"
    assert result["drift_detected"] is False


def test_cross_run_drift_detects_a_real_regime_shift(tmp_path) -> None:
    """ADWIN's default delta (0.002, calibrated for high-frequency
    streaming) turns out to need either far more points or a far larger
    jump than a run-history table will realistically ever have to fire at
    all -- checked directly, not assumed. check_cross_run_drift uses a
    deliberately looser delta=0.3 instead; this pins that it actually
    fires at a realistic history size."""
    db_path = tmp_path / "history.jsonl"
    for _ in range(20):
        record_run(db_path, _summary(exception_rate=0.01))
    for _ in range(20):
        record_run(db_path, _summary(exception_rate=0.60))  # a pipeline that's genuinely broken

    result = check_cross_run_drift(db_path)
    assert result["status"] == "evaluated"
    assert result["drift_detected"] is True


def test_cross_run_drift_does_not_false_positive_on_flat_noise(tmp_path) -> None:
    """The other half of the same tuning decision: delta=0.3 must not turn
    into a hair trigger on ordinary run-to-run fluctuation."""
    import random

    rng = random.Random(1)
    db_path = tmp_path / "history.jsonl"
    for _ in range(40):
        record_run(db_path, _summary(exception_rate=0.02 + rng.uniform(-0.005, 0.005)))

    result = check_cross_run_drift(db_path)
    assert result["drift_detected"] is False


def test_multiple_runs_accumulate_in_the_same_db(tmp_path) -> None:
    """A repeated `settlegraph run` against the same results dir should
    build real history, not overwrite the previous run."""
    db_path = tmp_path / "history.jsonl"
    record_run(db_path, _summary())
    record_run(db_path, _summary())
    record_run(db_path, _summary())
    assert len(list_runs(db_path)) == 3
