"""Tests for the SQLite run-history store."""

from __future__ import annotations

from settlegraph.engine.history_store import (
    check_cross_run_drift,
    get_metric_series,
    list_runs,
    record_run,
)


def _summary(precision: float = 1.0, exception_rate: float = 0.01) -> dict:
    return {
        "records": {"razorpay": 100, "bank": 100, "merchant": 100},
        "evaluation": {
            "precision": precision,
            "recall": 0.85,
            "f1": 0.9,
            "exception_rate": exception_rate,
            "false_match_rate": 0.0,
            "ai_assisted_matches": 0,
        },
        "throughput": {"records_per_second": 500.0},
        "drift": {"drift_detected": False},
    }


def test_record_and_list_round_trip(tmp_path) -> None:
    db_path = tmp_path / "history.db"
    run_id = record_run(db_path, _summary())
    runs = list_runs(db_path)
    assert len(runs) == 1
    assert runs[0]["run_id"] == run_id
    assert runs[0]["precision"] == 1.0
    assert runs[0]["total_records"] == 300


def test_record_run_accepts_a_pre_generated_run_id(tmp_path) -> None:
    """Code-review finding: summary.json needs to carry its own run_id
    *before* it's written to disk, which means the id has to exist before
    record_run is called, not be generated by it. record_run must accept
    (and actually use) a caller-supplied id rather than always minting its
    own."""
    db_path = tmp_path / "history.db"
    given_id = "fixed-test-id-1234"

    returned_id = record_run(db_path, _summary(), run_id=given_id)

    assert returned_id == given_id
    assert list_runs(db_path)[0]["run_id"] == given_id


def test_list_runs_on_missing_db_returns_empty_not_an_error(tmp_path) -> None:
    assert list_runs(tmp_path / "nonexistent.db") == []


def test_metric_series_is_chronological_oldest_first(tmp_path) -> None:
    db_path = tmp_path / "history.db"
    record_run(db_path, _summary(exception_rate=0.01))
    record_run(db_path, _summary(exception_rate=0.02))
    record_run(db_path, _summary(exception_rate=0.03))
    series = get_metric_series(db_path, "exception_rate")
    assert series == [0.01, 0.02, 0.03]


def test_unsupported_metric_is_rejected() -> None:
    import pytest

    with pytest.raises(ValueError, match="Unsupported metric"):
        get_metric_series(__import__("pathlib").Path("x.db"), "'; DROP TABLE runs;--")


def test_cross_run_drift_is_honest_about_insufficient_history(tmp_path) -> None:
    db_path = tmp_path / "history.db"
    record_run(db_path, _summary())
    record_run(db_path, _summary())
    result = check_cross_run_drift(db_path)
    assert result["status"] == "insufficient_history"
    assert result["drift_detected"] is False


def test_cross_run_drift_detects_a_real_regime_shift(tmp_path) -> None:
    """ADWIN's default delta (0.002, calibrated for high-frequency
    streaming) turns out to need either far more points or a far larger
    jump than a run-history table will realistically ever have to fire at
    all -- checked directly, not assumed. check_cross_run_drift uses a
    deliberately looser delta=0.3 instead; this pins that it actually
    fires at a realistic history size."""
    db_path = tmp_path / "history.db"
    for _ in range(20):
        record_run(db_path, _summary(exception_rate=0.01))
    for _ in range(20):
        record_run(db_path, _summary(exception_rate=0.60))  # a pipeline that's genuinely broken

    result = check_cross_run_drift(db_path)
    assert result["status"] == "evaluated"
    assert result["drift_detected"] is True


def test_cross_run_drift_does_not_false_positive_on_flat_noise(tmp_path) -> None:
    """The other half of the same tuning decision: delta=0.3 must not turn
    into a hair trigger on ordinary run-to-run fluctuation."""
    import random

    rng = random.Random(1)
    db_path = tmp_path / "history.db"
    for _ in range(40):
        record_run(db_path, _summary(exception_rate=0.02 + rng.uniform(-0.005, 0.005)))

    result = check_cross_run_drift(db_path)
    assert result["drift_detected"] is False


def test_multiple_runs_accumulate_in_the_same_db(tmp_path) -> None:
    """A repeated `settlegraph run` against the same results dir should
    build real history, not overwrite the previous run."""
    db_path = tmp_path / "history.db"
    record_run(db_path, _summary())
    record_run(db_path, _summary())
    record_run(db_path, _summary())
    assert len(list_runs(db_path)) == 3
